[auth]
usernames = ["coach", "patriot"]
names = ["Coach", "Patriot"]
passwords = [
  "$2b$12$Ea2YqwiuHDZ6c8GcJc7dDu3cC6aBO1syBEekgk.CxDExjwpYNtqpu",  # hashed password for dave
  "$2b$12$2IA5RqEoGZ34aXEiUAYpoeKlmpbR7voLkVH1BWvZ79dCa9Q5880Ku"   # hashed password for jane
]

[auth.cookie]
name = "Patriot_Logger"
key = "sign_in_key"
expiry_days = 1

[credentials.usernames.ben]
email = "fortressben@gmail.com"
name = "Ben"
password = "$2b$12$2IA5RqEoGZ34aXEiUAYpoeKlmpbR7voLkVH1BWvZ79dCa9Q5880Ku"

